name: split_expense
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.7+12

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  chips_choice: ^3.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  share_plus: ^10.0.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/split.webp"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/split.webp"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/split.webp"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/split.webp"

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
